import { insertMany } from "./mongo.js"

const data = [
    {
        name: "IBM Fullstack Javascript Developer Professional",
        img: "/ibm-full-stack-javascript-developer-professional-ce.png",
        url: "https://www.credly.com/badges/2d0a7323-b23f-4819-8f04-fbbee9826a2c/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Square",
        type: "Badges",
    },
    {
        name: "Application Development using Microservices and Serverless",
        img: "/application-development-using-microservices-and-ser.png",
        url: "https://www.credly.com/badges/f5f2b869-7b15-42da-aa21-90e9ce642d2e/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Cloud Native, DevOps, Agile & NoSQL Essentials",
        img: "/cloud-native-devops-agile-nosql-essentials.png",
        url: "https://www.credly.com/badges/f9412173-1ff1-4fbf-b76d-297463dcd536/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",

    },
    {
        name: "Intermediate Back-end Development: Node & MongoDB",
        img: "/intermediate-back-end-development-node-mongodb.png",
        url: "https://www.credly.com/badges/19c5c4c9-a9b1-47e1-920f-c1f84eb623d3/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Containers & Kubernetes Essentials",
        img: "/containers-kubernetes-essentials.1.png",
        url: "https://www.credly.com/badges/71cd6acb-b7c9-4a49-9096-cef1124e7cc3/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Node and Express Essentials",
        img: "/node-and-express-essentials.png",
        url: "https://www.credly.com/badges/e796a604-f044-41ca-be26-047f02d531e8/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Front-end Development with React V2",
        img: "/front-end-development-with-react-v2.1.png",
        url: "https://www.credly.com/badges/180185b7-b8dd-4fd0-b4e6-81d2e8f8703b/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "JavaScript Programming Essentials",
        img: "/javascript-programming-essentials.png",
        url: "https://www.credly.com/badges/b5111860-9bc8-490e-a96a-7f5fec0c8f45/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Git and GitHub Essentials",
        img: "/git-and-github-essentials.1.png",
        url: "https://www.credly.com/badges/f1a9cc87-2f74-42df-967e-467f5b60c038/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Introduction to HTML, CSS, & JavaScript",
        img: "/introduction-to-html-css-javascript.png",
        url: "https://www.credly.com/badges/5f426972-f3fc-47d3-baf2-78dacfb4dc71/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Software Engineering Essentials",
        img: "/software-engineering-essentials.png",
        url: "https://www.credly.com/badges/04d7c713-f417-4a41-bb65-2e353a89b394/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "JavaScript Full Stack Capstone Project",
        img: "/javascript-full-stack-capstone-project.png",
        url: "https://www.credly.com/badges/29e005e6-81bc-449d-a304-8e497749addd/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Software Developer Career Guide and Interview Preparation",
        img: "/software-developer-career-guide-and-interview-prepa.png",
        url: "https://www.credly.com/badges/902ef6c3-704f-40de-ba7a-7cd4a53dcfc3/public_url",
        issuer: "Coursera",
        provided_by: "Credly",
        shape: "Circle",
        type: "Badges",
    },
    {
        name: "Introduction to Software Engineering",
        img: "/Screenshot 2025-05-03 234716.png",
        url: "https://coursera.org/verify/JMUC8UGWNUAA",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Introduction to HTML, CSS, & JavaScript",
        img: "/Screenshot 2025-05-03 234924.png",
        url: "https://coursera.org/verify/S4R5M3G4RJ7K",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Getting Started with Git and GitHub",
        img: "/Screenshot 2025-05-03 235030.png",
        url: "https://coursera.org/verify/MPA83TGLOBBU",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "JavaScript Programming Essentials",
        img: "/Screenshot 2025-05-03 235123.png",
        url: "https://coursera.org/verify/ZFKNPRA5Z6KT",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Developing Front-End Apps with React",
        img: "/Screenshot 2025-05-03 235218.png",
        url: "https://coursera.org/verify/Y2H30G0O2STN",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Developing Back-End Apps with Node.js and Express",
        img: "/Screenshot 2025-05-03 235314.png",
        url: "https://coursera.org/verify/IG8SW56DQ6QF",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Get Started with Cloud Native, DevOps, Agile, and NoSQL",
        img: "/Screenshot 2025-05-03 235434.png",
        url: "https://coursera.org/verify/K2ABAPSGIRN6",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Introduction to Containers w/ Docker, Kubernetes & OpenShift",
        img: "/Screenshot 2025-05-03 235609.png",
        url: "https://coursera.org/verify/F49WZHE18NG2",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Application Development using Microservices and Serverless",
        img: "/Screenshot 2025-05-03 235705.png",
        url: "https://coursera.org/verify/SM2RK5OM4DOX",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Node.js & MongoDB: Developing Back-end Database Applications",
        img: "/Screenshot 2025-05-03 235831.png",
        url: "https://coursera.org/verify/P6NPF5YNB79O",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "Software Developer Career Guide and Interview Preparation",
        img: "/Screenshot 2025-05-04 000000.png",
        url: "https://coursera.org/verify/3H46B5EHQK3B",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
    {
        name: "IBM Full-Stack JavaScript Developer",
        img: "/Screenshot 2025-05-04 000105.png",
        url: "https://coursera.org/verify/professional-cert/6LXE1U1UGEV8",
        issuer: "IBM",
        provided_by: "Coursera",
        shape: "Square",
        type: "Cert",
    },
]

await insertMany(data).then(d => console.log(d))
